name: Build data (Excel → CSV por centro)

on:
  workflow_dispatch: {}   # permitir lanzarlo a mano
  schedule:
    # 06:30 UTC ≈ 07:30-08:30 en España (según horario de verano)
    - cron: "30 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Ejecutar conversión
        run: |
          python scripts/build_data.py

      - name: Commit & push si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Solo si hay cambios
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "data: refresh Articulos.csv por centro (auto)"
            git push
          else
            echo "Sin cambios para commitear."
          fi
