name: Build data (Excel → CSV por centro)

on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *" # 06:30 UTC (07:30/08:30 España)

permissions:
  contents: write  # ← imprescindible para poder hacer push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Mostrar árbol de carpetas
        run: |
          echo "=== ROOT ==="
          ls -la
          echo "=== data ==="
          ls -la data || true
          echo "=== data/incoming ==="
          ls -la "data/incoming" || true
          echo "=== scripts ==="
          ls -la scripts || true

      - name: Comprobación de ficheros requeridos
        run: |
          set -e
          test -f "scripts/build_data.py" || { echo "::error::No existe scripts/build_data.py"; exit 1; }
          test -f "data/incoming/Base articulos precio.xlsx" || { echo "::error::Falta data/incoming/Base articulos precio.xlsx"; exit 1; }
          test -f "data/incoming/Importacion Stock.xlsx" || { echo "::error::Falta data/incoming/Importacion Stock.xlsx"; exit 1; }
          test -f "data/incoming/Lista proveedores_05092025.xlsx" || { echo "::error::Falta data/incoming/Lista proveedores_05092025.xlsx"; exit 1; }

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -V
          pip install -U pip
          pip install pandas openpyxl numpy pyarrow

           - name: Inspección rápida de los Excel
        shell: bash
        run: |
          set -e
          cat > /tmp/inspect_excel.py << 'PY'
          import pandas as pd

          files = [
              "data/incoming/Base articulos precio.xlsx",
              "data/incoming/Importacion Stock.xlsx",
              "data/incoming/Lista proveedores_05092025.xlsx",
          ]

          for p in files:
              print(f">>> {p}")
              try:
                  xl = pd.ExcelFile(p)
                  print("   hojas:", xl.sheet_names)
                  df = xl.parse(xl.sheet_names[0], nrows=2)
                  print("   columnas:", list(df.columns))
              except Exception as e:
                  print("!!! ERROR leyendo", p, "->", e)
                  raise
          PY

          python /tmp/inspect_excel.py
