name: Build data (CSV → por centro)

on:
  workflow_dispatch:
  schedule:
    # 05:30 UTC ≈ 07:30 España (ajústalo si quieres)
    - cron: "30 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mostrar árbol (top)
        run: |
          ls -la
          echo ""
          echo "imports/"
          ls -la imports || true

      - name: Comprobación de ficheros requeridos
        run: |
          set -e
          test -f imports/base_articulos.csv || (echo "Falta imports/base_articulos.csv" && exit 1)
          test -f imports/stock_por_almacen.csv || (echo "Falta imports/stock_por_almacen.csv" && exit 1)
          # Los overrides son opcionales:
          # overrides/ean/*.json  y overrides/images/*.json

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Ejecutar ingesta (con logs verbosos)
        run: |
          python scripts/build_data.py --verbose

      - name: Comprobar cambios generados
        id: diff
        run: |
          set +e
          git status --porcelain
          CHANGES=$(git status --porcelain | wc -l)
          echo "changes=$CHANGES" >> $GITHUB_OUTPUT
          set -e

      - name: Commit & push datos (si hubo cambios)
        if: steps.diff.outputs.changes != '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "build: regenerar Articulos.csv por centro (CSV imports)"
          git push
